[package]
name = "sort_exercice"
version = "0.1.0"
authors = ["stephaneworkspace <stephane@bressani.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "2.5.1"
